- name: Install mysql client
  apt:
    name: libmysqlclient-dev
    state: latest
- name: 'Download redmine package'
  get_url:
    url: 'https://www.redmine.org/releases/redmine-{{ redmine_version }}.tar.gz'
    dest: /tmp/redmine.tar.gz
    sha256sum: '{{ redmine_checksum }}'
  register: download_redmine_package
- name: 'Create directory'
  file:
    path: /opt/redmine/
    state: directory
- name: 'Unarchive redmine package'
  unarchive:
    src: /tmp/redmine.tar.gz
    dest: /opt/redmine/
    extra_opts: [--strip-components=1]
    remote_src: yes
  when: download_redmine_package.changed
- name: Setup configuration
  shell:
    chdir: /opt/redmine
    cmd: |
      cat config/database.yml.example \
        | yq -y ".production.adapter = \"mysql2\"" \
        | yq -y ".production.host = \"127.0.0.1\"" \
        | yq -y ".production.username = \"{{ redmine_database_username }}\"" \
        | yq -y ".production.password = \"{{ redmine_database_password }}\"" > config/database.yml
- name: Transfer unicorn configuration
  copy:
    src: unicorn.rb
    dest: /opt/redmine/config/unicorn.rb
- name: Check exists unicorn module of Gemfile
  shell:
    chdir: /opt/redmine
    cmd: grep 'gem "unicorn"' ./Gemfile | wc -l
  register: exists_unicorn_count
  changed_when: no
- name: Add unicorn module to Gemfile
  shell:
    chdir: /opt/redmine
    cmd: echo 'gem "unicorn"' >> ./Gemfile
  when: exists_unicorn_count.stdout == '0'
- name: Check exists github hook module of Gemfile
  shell:
    chdir: /opt/redmine
    cmd: grep 'gem "redmine_github_hook"' ./Gemfile | wc -l
  register: exists_redmine_github_hook_count
  changed_when: no
- name: Add github hook module to Gemfile
  shell:
    chdir: /opt/redmine
    cmd: echo 'gem "redmine_github_hook"' >> ./Gemfile
  when: exists_redmine_github_hook_count.stdout == '0'
- name: Install dependencies
  environment:
    BUNDLE_PATH: /opt/redmine/vendor/bundle
  shell:
    chdir: /opt/redmine
    cmd: bundle install --without development test rmagick
- name: Generate secret token
  shell:
    chdir: /opt/redmine
    cmd: bundle exec rake generate_secret_token
- name: Execute migration
  environment:
    RAILS_ENV: production
  shell:
    chdir: /opt/redmine
    cmd: bundle exec rails db:migrate
- name: Clone theme
  git: 
    repo: https://github.com/farend/redmine_theme_farend_bleuclair.git
    dest: /opt/redmine/public/themes/bleuclair
    version: '{{ redmine_theme_farend_bleuclair_version }}'
  when: redmine_theme_farend_bleuclair_version is defined
- name: Start service
  systemd:
    name: redmine
    daemon_reload: yes
    state: restarted
