nginx_config_http_template_enable: true
nginx_config_http_template:
  default:
    conf_file_name: default.conf
    conf_file_location: /etc/nginx/conf.d/
    servers:
      default_http:
        listen:
          listen_local_host:
            port: 80
        server_name: '{{ server_name }}'
        error_page: /usr/share/nginx/html
        web_server:
          locations:
            default:
              location: /
              html_file_location: '/usr/share/nginx/html'
              html_file_name: index.html
              autoindex: false
              returns:
                return301:
                  code: 301
                  url: 'https://{{ server_name }}$request_uri'
          http_demo_conf: false
      default_https:
        listen:
          listen_local_host:
            port: 443
            ssl: true
            opts: [http2]
        server_name: '{{ server_name }}'
        access_log:
          - name: main
            location: '/var/log/nginx/{{ server_name }}_access.log'
        error_log:
          location: '/var/log/nginx/{{ server_name }}_error.log'
          level: warn
        error_page: /usr/share/nginx/html
        ssl:
          cert: '/etc/letsencrypt/live/{{ server_name }}/fullchain.pem'
          key: '/etc/letsencrypt/live/{{ server_name }}/privkey.pem'
          ciphers: HIGH:!aNULL:!MD5
          prefer_server_ciphers: true
          session_cache: shared:SSL:1m
          session_timeout: 5m
        web_server:
          locations:
            default:
              location: /
              html_file_location: '/usr/share/nginx/html'
              html_file_name: index.html
              autoindex: false
          http_demo_conf: false
  redmine:
    conf_file_name: redmine.conf
    conf_file_location: /etc/nginx/conf.d/
    servers:
      redmine_http:
        listen:
          listen_local_host:
            port: 80
        server_name: '{{ redmine_server_name }}'
        web_server:
          locations:
            default:
              location: /
              html_file_location: '/usr/share/nginx/html'
              html_file_name: index.html
              autoindex: false
              returns:
                return301:
                  code: 301
                  url: 'https://{{ redmine_server_name }}$request_uri'
          http_demo_conf: false
      redmine_https:
        listen:
          listen_local_host:
            port: 443
            ssl: true
            opts: [http2]
        server_name: '{{ redmine_server_name }}'
        access_log:
          - name: main
            location: '/var/log/nginx/{{ redmine_server_name }}_access.log'
        error_log:
          location: '/var/log/nginx/{{ redmine_server_name }}_error.log'
          level: warn
        error_page: /usr/share/nginx/html
        ssl:
          cert: '/etc/letsencrypt/live/{{ redmine_server_name }}/fullchain.pem'
          key: '/etc/letsencrypt/live/{{ redmine_server_name }}/privkey.pem'
          ciphers: HIGH:!aNULL:!MD5
          prefer_server_ciphers: true
          session_cache: shared:SSL:1m
          session_timeout: 5m
        reverse_proxy:
          locations:
            redmine:
              location: /
              proxy_pass: 'http://redmine'
              proxy_set_header:
                header_host:
                  name: Host
                  value: $host
                header_x_real_ip:
                  name: X-Real-IP
                  value: $remote_addr
                header_x_forwarded_for:
                  name: X-Forwarded-For
                  value: $proxy_add_x_forwarded_for
                header_x_forwarded_proto:
                  name: X-Forwarded-Proto
                  value: $scheme
    upstreams:
      redmine:
        name: redmine
        sticky_cookie: false
        custom_options:
          - server unix:/opt/redmine/tmp/redmine.sock fail_timeout=0;
        servers: []
  jenkins:
    conf_file_name: jenkins.conf
    conf_file_location: /etc/nginx/conf.d/
    servers:
      jenkins_http:
        listen:
          listen_local_host:
            port: 80
        server_name: '{{ jenkins_server_name }}'
        web_server:
          locations:
            default:
              location: /
              html_file_location: '/usr/share/nginx/html'
              html_file_name: index.html
              autoindex: false
              returns:
                return301:
                  code: 301
                  url: 'https://{{ jenkins_server_name }}$request_uri'
          http_demo_conf: false
      jenkins_https:
        listen:
          listen_local_host:
            port: 443
            ssl: true
            opts: [http2]
        server_name: '{{ jenkins_server_name }}'
        access_log:
          - name: main
            location: '/var/log/nginx/{{ jenkins_server_name }}_access.log'
        error_log:
          location: '/var/log/nginx/{{ jenkins_server_name }}_error.log'
          level: warn
        error_page: /usr/share/nginx/html
        ssl:
          cert: '/etc/letsencrypt/live/{{ jenkins_server_name }}/fullchain.pem'
          key: '/etc/letsencrypt/live/{{ jenkins_server_name }}/privkey.pem'
          ciphers: HIGH:!aNULL:!MD5
          prefer_server_ciphers: true
          session_cache: shared:SSL:1m
          session_timeout: 5m
        reverse_proxy:
          locations:
            jenkins:
              location: /
              proxy_pass: 'http://jenkins'
              proxy_set_header:
                header_host:
                  name: Host
                  value: $host
                header_x_real_ip:
                  name: X-Real-IP
                  value: $remote_addr
                header_x_forwarded_for:
                  name: X-Forwarded-For
                  value: $proxy_add_x_forwarded_for
                header_x_forwarded_proto:
                  name: X-Forwarded-Proto
                  value: $scheme
    upstreams:
      jenkins:
        name: jenkins
        sticky_cookie: false
        servers:
          jenkins:
            address: localhost
            port: '{{ jenkins_http_port }}'
            health_check: fail_timeout=0
