- hosts: web
  become: yes
  roles:
    - timezone
    - locale
    - yq
    - add_user
    - nginxinc.nginx
    - nginxinc.nginx_config
    - geerlingguy.mysql
    - geerlingguy.ruby
    - systemd
    - redmine
    - anxs.tmpreaper
  vars_files:
    - vars/user.yml
    - vars/nginx.yml
    - vars/ruby.yml
    - vars/mysql.yml
    - vars/redmine.yml
    - vars/tmpreaper.yml
